package com.example.backend.entity.enums;

public enum Habitat {
    ANY, ARCTIC, COASTAL, DESERT, FOREST, GRASSLAND, HILL, MOUNTAIN, NONE,
    PLANAR_ABYSS, PLANAR_ACHERON, PLANAR_ELEMENTAL_PLANE_OF_AIR, PLANAR_ARBOREA,
    PLANAR_ARCADIA, PLANAR_ASTRAL_PLANE, PLANAR_BEASTLANDS, PLANAR_BYTOPIA, PLANAR_CARCERI,
    PLANAR_ELEMENTAL_PLANE_OF_EARTH, PLANAR_ELEMENTAL_CHAOS, PLANAR_ELYSIUM, PLANAR_ETHEREAL_PLANE,
    PLANAR_FEYWILD, PLANAR_ELEMENTAL_PLANE_OF_FIRE, PLANAR_GEHENNA, PLANAR_HADES, PLANAR_LIMBO,
    PLANAR_MRCHANUS, PLANAR_MOUNT_CELESTIA, PLANAR_NINE_HELLS, PLANAR_PANDEMONIUM, PLANAR_SHADOWFELL,
    PLANAR_ELEMENTAL_PLANE_OF_WATER, PLANAR_YSGARD, SWAMP, UNDERDARK, UNDERWATER, URBAN, OTHER_PLANE
}
