package com.example.backend.entity.enums;

public enum Tag {
    AARAKOCRA, ANGEL, ANY_RACE, ARCHFEY, BARD, BEHOLDER, BULLYWUG, CATTLE, CHANGELING, CHROMATIC,
    CLERIC, CLOUD_GIANT, DEMON, DERRO, DEVIL, DINOSAUR, DRAGONBORN, DROW, DRUID, DWARF, ELF,
    FIRE_GIANT, FIRENEWT, FROST_GIANT, GEM, GENASI, GENIE, GITH, GNOLL, GNOME, GOBLINOID, GOLIATH,
    GRIMLOCK, GRIPPLI, GRUNG, HAG, HALF_BLACK_DRAGON, HALF_DRAGON, HALF_ELF, HALF_ORC, HALFLING,
    HARENGON, HEALER, HILL_GIANT, HUMAN, INEVITABLE, KALASHTAR, KENDER, KENKU, KOBOLD, KRAUL,
    KUO_TOA, LAVA_CHILD, LEONIN, LIZARDFOLK, LOCATHAH, MAGE, MEAZEL, MEDUSA, MERFOLK, METALLIC,
    MIND_FLAYER, MINOTAUR, MONGRELFOLK, MONK, MOONSTONE, NAGPA, ORC, PALADIN, QUAGGOTH, SAHUAGIN,
    SAURIAL, SHADAR_KAI, SHAPECHANGER, SHIFTER, SIMIC_HYBRID, SORCERER, STONE_GIANT, STORM_GIANT,
    SWARM, TABAXI, THRI_KREEN, TIEFLING, TITAN, TORTLE, TRITON, TROGLODYTE, VAMPIRE, WARFORGED,
    WARLOCK, WIZARD, XVART, YOUNG_GEM, YUAN_TI, YUGOLOTH;
}
